# Use uma imagem do OpenJDK como base
FROM openjdk:17-jdk-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o JAR da aplicação para o container
COPY target/vendas-api.jar vendas-api.jar

# Exponha a porta que o Spring Boot irá rodar
EXPOSE 8080

# Comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "vendas-api.jar"]
